// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index(appContent templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title></title><link href=\"/statics/picocss/pico.colors.min.css\" rel=\"stylesheet\"><link href=\"/statics/picocss/pico.amber.min.css\" rel=\"stylesheet\"><link href=\"/statics/global.styles.css\" rel=\"stylesheet\"><link rel=\"icon\" type=\"image/x-icon\" href=\"/statics/favicon/favicon.ico\"><script src=\"/statics/htmx/htmx.v2.0.4.min.js\"></script></head><body><nav style=\"\n                padding: 0 var(--padding-increment) var(--padding-increment) var(--padding-increment);\n                background-color: var(--pico-background-color);\n                position: sticky;\n                top: 0;\n                z-index: 100;\n            \"><ul><li><strong>Demo Application</strong></li></ul><ul><li><button hx-target=\"#app-content\" hx-get=\"/canvasapp/app?source=nav\" hx-push-url=\"/canvasapp/app\">Canvas App</button></li><li><button hx-target=\"#app-content\" hx-get=\"/todolist/app?source=nav\" hx-push-url=\"/todolist/app\">Todo List</button></li><li><button class=\"outline\">Login</button></li></ul></nav><div id=\"app-content\" style=\"overflow: hidden\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if appContent != nil {
			templ_7745c5c3_Err = appContent.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
